#nacos配置方式
spring:
  application:
    name: usr-service
  cloud:
    nacos:
      discovery:
        server-addr: 47.113.205.0:8848
      config:
        server-addr: 47.113.205.0:8848
  #        cluster-name: xx #自定义集群名称
#  配置文件配置：
  datasource:
    # 配置数据源类型
    type:
      com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.113.205.0:3306/DMicro?useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: nibaba
    # 初始化，最小，最大连接数
    initialSize: 3
    minidle: 3
    maxActive: 18
    # 获取数据库连接等待的超时时间
    maxWait: 60000
    # 配置多久进行一次检测，检测需要关闭的空闲连接 单位毫秒
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1 FROM dual
    # 配置监控统计拦截的filters,去掉后，监控界面的sql无法统计
    filters: stat,wall,
  redis:
    # redis服务器地址（默认为localhost）
    host: 47.113.205.0
    # redis端口（默认为6379）
    port: 6379
    # redis访问密码（默认为空）
    password:
    # redis连接超时时间（单位为毫秒）
    timeout: 2000
    # redis连接池配置
    database: 3
    jedis:
      pool:
        # 最大可用连接数（默认为8，负数表示无限）
        max-active: 16
        # 最大空闲连接数（默认为8，负数表示无限）
        max-idle: 16
        # 最小空闲连接数（默认为0，该值只有为正数才有作用）
        min-idle: 8
        # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
        max-wait: -1
    lettuce:
      shutdown-timeout: 60
#      pool:
#        max-wait: 30000

server:
  port: 5050
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  #mapper.xml位置
  mapper-locations: classpath*:/mybatis/mapper/**Mapper.xml
feign:
  client:
    config:
      default:
        connectTimeout: 300000
        readTimeout: 300000
# 设置ribbon超时时间
ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000