server:
  port: 21000
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: r-xxxservice #第一个路由标识,必须唯一
            uri: lb://xxxservice #路由的目标地址(服务名称或者ip地址都行)  lb代表loadbalance
            predicates: #路由断言,判断请求是否符合规则
              - Path=/xxx/** #路径断言,判断路径是否以/xxx开头,如果是则符合
            filters:
              - AddRequestHeader = key,value #过滤器:加入请求头key,值value
              - id: r-xxxservice #第二个路由标识,必须唯一
                uri: lb://xxxservice #路由的目标地址
                predicates: #路由断言,判断请求是否符合规则
                  - Path=/xxx/** #路径断言,判断路径是否以/xxx开头,如果是则符合
      default-filters: #默认过滤器,会对所有的路由请求都生效
        - AddRequestHeader = key,value #过滤器:加入请求头key,值value
      globalcors: #全局跨域处理
        add-to-simple-url-handler-mapping: true  #解决options请求被拦截问题
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:8080"
              - "http://xxx"
            allowedHeaders: "*" #允许在请求中携带的头信息
            allowdMethods:  #允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowCredentials: true #是否允许携带cookie
            maxAge: 360000 #这次跨域检测的有效期