server:
  port: 21000
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 47.113.205.0:8848
    gateway:
      routes:
        - id: usr-service #第一个路由标识,必须唯一
          uri: lb://usr-service #路由的目标地址(服务名称或者ip地址都行)  lb代表loadbalance
          predicates: #路由断言,判断请求是否符合规则
            - Path=/user/** #路径断言,判断路径是否以/xxx开头,如果是则符合
        - id: art-service
          uri: lb://art-service
          predicates:
            - Path=/article/**
        - id: com-service
          uri: lb://com-service
          predicates:
            - Path=/comment/**
        - id: topic-service
          uri: lb://topic-service
          predicates:
            - Path=/topic/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOrigins: "*"
            allowCredentials: true
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTION
      default-filters:
        - DedupeResponseHeader=Vary Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_UNIQUE
        - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_FIRST
